version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scimma-web
    command: --bind=0.0.0.0:5000 --worker-class=gevent --workers=2 --timeout=300 --access-logfile=- --error-logfile=- 'app:create_app()'
    ports:
      - "5000:5000"
    depends_on:
      - db
  ingest:
    build: .
    container_name: scimma-ingest
    command: python ingest.py
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    container_name: scimma-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=scimma
      - POSTGRES_PASSWORD=scimma
      - POSTGRES_DB=scimma
  hopskotch:
    image: scimma/server
    container_name: hopskotch
    ports:
      - "9092:9092"
    entrypoint: ["/root/runServer", "--noSecurity"]
    volumes:
      - shared:/root/shared

volumes:
  postgres_data:
  shared: